/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        setTitle("Administrador");
        setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;		
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon (getClass().getResource("../img/icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_RegistrarParqueadero = new javax.swing.JButton();
        btn_ConsultarEntrada = new javax.swing.JButton();
        btn_EstadisticasIngreso = new javax.swing.JButton();
        btn_ValorRecaudado = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sistema22.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 100));

        btn_RegistrarParqueadero.setText("Registrar  parqueadero");
        btn_RegistrarParqueadero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_RegistrarParqueaderoMouseClicked(evt);
            }
        });
        btn_RegistrarParqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarParqueaderoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_RegistrarParqueadero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 40));
        btn_RegistrarParqueadero.getAccessibleContext().setAccessibleName("Registrar parqueadero");

        btn_ConsultarEntrada.setText("Consultar entrada y salida de vehículos");
        btn_ConsultarEntrada.setAlignmentY(0.0F);
        btn_ConsultarEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ConsultarEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ConsultarEntradaMouseClicked(evt);
            }
        });
        btn_ConsultarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultarEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ConsultarEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 230, 40));

        btn_EstadisticasIngreso.setText("Estadísticas ingreso vehículos");
        btn_EstadisticasIngreso.setToolTipText("");
        btn_EstadisticasIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EstadisticasIngresoMouseClicked(evt);
            }
        });
        getContentPane().add(btn_EstadisticasIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 150, 40));

        btn_ValorRecaudado.setText("Valor recaudado por periodos");
        btn_ValorRecaudado.setAutoscrolls(true);
        btn_ValorRecaudado.setBorderPainted(false);
        btn_ValorRecaudado.setDefaultCapable(false);
        btn_ValorRecaudado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ValorRecaudadoMouseClicked(evt);
            }
        });
        getContentPane().add(btn_ValorRecaudado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 230, 40));

        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit-P.png"))); // NOI18N
        btn_Salir.setContentAreaFilled(false);
        btn_Salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit-G.png"))); // NOI18N
        btn_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SalirMouseClicked(evt);
            }
        });
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ConsultarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultarEntradaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_ConsultarEntradaActionPerformed

    private void btn_RegistrarParqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarParqueaderoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn_RegistrarParqueaderoActionPerformed

    private void btn_EstadisticasIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EstadisticasIngresoMouseClicked
        Estadisticas miEstadistica = new Estadisticas();
        miEstadistica.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_EstadisticasIngresoMouseClicked

    private void btn_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SalirMouseClicked
        // TODO add your handling code
    }//GEN-LAST:event_btn_SalirMouseClicked

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        Ingreso miIngreso = new Ingreso();
        miIngreso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_RegistrarParqueaderoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RegistrarParqueaderoMouseClicked
        // TODO add your handling code here:
        RegistrarParqueadero registrarParqueader = new RegistrarParqueadero();
        registrarParqueader.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_RegistrarParqueaderoMouseClicked

    private void btn_ConsultarEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConsultarEntradaMouseClicked
        // TODO add your handling code here:
        ConsultaEntradaSalidaDeVehiculo consulta = new ConsultaEntradaSalidaDeVehiculo();
        consulta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ConsultarEntradaMouseClicked

    private void btn_ValorRecaudadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ValorRecaudadoMouseClicked
        // TODO add your handling code here:
        RecaudoPeriodos recaudoPeriodos = new RecaudoPeriodos();
        recaudoPeriodos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ValorRecaudadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ConsultarEntrada;
    private javax.swing.JButton btn_EstadisticasIngreso;
    private javax.swing.JButton btn_RegistrarParqueadero;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton btn_ValorRecaudado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
