/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mundo.Automoviles;
import mundo.Bicicletas;
import mundo.Controlador;
import mundo.Motocicletas;
import mundo.Vehiculo;

/**
 *
 * @author felip
 */
public class TipoVehiculo extends javax.swing.JFrame {
    private int codigoParqueadero;
    /**
     * Creates new form TipoVehiculo
     */
    public TipoVehiculo() {
        initComponents();
    }
    public TipoVehiculo(int codigoParqueadero){
        this.codigoParqueadero = codigoParqueadero;
        initComponents();
        setTitle("Tipo Vehiculo");
        setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;		
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon (getClass().getResource("../img/icon.png")).getImage());
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipo_vehiculo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        validar_disponibilidad = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tipo_vehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automoviles", "Motocicletas", "Bicicletas" }));
        tipo_vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_vehiculoActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de vehiculo");

        validar_disponibilidad.setText("Validar disponibilidad");
        validar_disponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validar_disponibilidadActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit-P.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit-G.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(tipo_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(validar_disponibilidad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(tipo_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(validar_disponibilidad)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipo_vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_vehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_vehiculoActionPerformed

    private void validar_disponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validar_disponibilidadActionPerformed
            String tipoVehiculo;
            tipoVehiculo = tipo_vehiculo.getSelectedItem().toString();
            Vehiculo miVehiculo = new Vehiculo();
            if(tipoVehiculo.equals("Automoviles")){
                Automoviles miCarrito = new Automoviles();
                miCarrito.setTipoVehiculo(tipoVehiculo);
                miVehiculo = miCarrito;
            }else if(tipoVehiculo.equals("Motocicletas")){
                
                Motocicletas miMotico = new Motocicletas();
                miMotico.setTipoVehiculo(tipoVehiculo);
                miVehiculo = miMotico;
                
            }else if(tipoVehiculo.equals("Bicicletas")){
            
                Bicicletas miBicicletita = new Bicicletas();
                miBicicletita.setTipoVehiculo(tipoVehiculo);
                miVehiculo = miBicicletita;
                
            }
            Controlador controlador = new Controlador();
            boolean cupo =controlador.verificarCupo(tipoVehiculo, codigoParqueadero);
            if(cupo==true){
                JOptionPane.showMessageDialog(null, "Si hay cupos disponibles");
                
                TipoDeRegistro registro = new TipoDeRegistro(codigoParqueadero, miVehiculo);
                registro.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "NO hay cupos disponibles");
            }
            
            
        
        // TODO add your handling code here:
        /**VistaArea areaVehiculo = new VistaArea(null,0);
        VistaArea areaMotos = new VistaArea(null,0);
        VistaArea areaBicis = new VistaArea(null,0);*/
    }//GEN-LAST:event_validar_disponibilidadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Empleado empleado = new Empleado(codigoParqueadero);
        empleado.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> tipo_vehiculo;
    private javax.swing.JButton validar_disponibilidad;
    // End of variables declaration//GEN-END:variables
}
